

# Permalinks
permalink:           /:title

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         Las Críticas del doctor Mabuse 
title:               Las Críticas del doctor Mabuse
tagline:             'tagline'
description:         'Veo histórias y escribo sobre ellas'
url:                 ''
rss:                 rss feed url

baseurl:             /criticas_del_doctor_Mabuse
baseurl_posts_img:   'assets/images/posts/'
baseurl_featured_img: 'assets/images/hero/'
baseurl_featured_thumbnail: 'assets/images/thumbnail/'
baseurl_javascripts: 'assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Sergio Jiménez Corominas
  url:            	 your site url
  facebook:          username
  twitter:           sergiojimenez


# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
